const app = document.getElementById('app'), modal = document.getElementById('modal'), toast = document.getElementById('toast');
if (!window.I18n) { const language = document.createElement('script'); language.src = 'lang.js'; language.onload = () => { const ui = document.createElement('script'); ui.src = 'language-ui.js'; document.head.append(ui); }; document.head.append(language); }
const params = new URLSearchParams(location.search), projectId = params.get('project');
const escape = value => String(value || '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function notify(message) { toast.textContent = message; toast.classList.remove('hidden'); setTimeout(() => toast.classList.add('hidden'), 2800); }
function closeModal(){ modal.classList.add('hidden'); modal.innerHTML = ''; }
function formModal(title, body, onSubmit) { modal.innerHTML = `<form id="editor" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div class="mb-5 flex items-center justify-between"><h2 class="font-geist text-xl font-bold">${title}</h2><button type="button" onclick="closeModal()" class="text-slate-500"><span class="material-symbols-outlined">close</span></button></div>${body}<div class="mt-6 flex justify-end gap-3"><button type="button" onclick="closeModal()" class="rounded-lg border border-line px-4 py-2 font-semibold">Batal</button><button class="rounded-lg bg-brand px-4 py-2 font-semibold text-white">Simpan</button></div></form>`; modal.classList.remove('hidden'); document.getElementById('editor').onsubmit = event => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }; }
function projectForm(project = {}) { return `<label class="block text-sm font-semibold">Nama Project<input required name="name" value="${escape(project.name)}" class="mt-1 w-full rounded-lg border border-line px-3 py-2 font-normal" maxlength="80"></label><label class="mt-4 block text-sm font-semibold">Deskripsi<textarea name="description" class="mt-1 min-h-24 w-full rounded-lg border border-line px-3 py-2 font-normal" maxlength="500">${escape(project.description)}</textarea></label>`; }
function taskForm(task = {}) { return `<label class="block text-sm font-semibold">Judul Task<input required name="title" value="${escape(task.title)}" class="mt-1 w-full rounded-lg border border-line px-3 py-2 font-normal" maxlength="100"></label><label class="mt-3 block text-sm font-semibold">Deskripsi<textarea name="description" class="mt-1 min-h-20 w-full rounded-lg border border-line px-3 py-2 font-normal" maxlength="500">${escape(task.description)}</textarea></label><div class="mt-3 grid grid-cols-2 gap-3"><label class="text-sm font-semibold">Priority<select name="priority" class="mt-1 w-full rounded-lg border border-line px-3 py-2 font-normal">${['Low','Medium','High'].map(x=>`<option ${task.priority===x?'selected':''}>${x}</option>`)}</select></label><label class="text-sm font-semibold">Status<select name="status" class="mt-1 w-full rounded-lg border border-line px-3 py-2 font-normal">${[['todo','To Do'],['progress','In Progress'],['review','Review'],['done','Done']].map(([v,n])=>`<option value="${v}" ${task.status===v?'selected':''}>${n}</option>`)}</select></label></div><div class="mt-3 grid grid-cols-2 gap-3"><label class="text-sm font-semibold">Due Date<input type="date" name="due_date" value="${task.due_date||''}" class="mt-1 w-full rounded-lg border border-line px-3 py-2 font-normal"></label><label class="text-sm font-semibold">Assignee<input name="assignee" value="${escape(task.assignee)}" class="mt-1 w-full rounded-lg border border-line px-3 py-2 font-normal" placeholder="Optional"></label></div>`; }
function renderProjects(){ const projects = ProjectStore.projects(); app.innerHTML = `<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="mb-2 text-sm font-semibold uppercase tracking-wider text-primary">Workspace</p><h2 class="font-geist text-3xl font-bold">Daftar Project</h2><p class="mt-2 text-slate-600">Kelola project dan pekerjaan tim dalam satu tempat.</p></div><button onclick="newProject()" class="inline-flex items-center justify-center gap-2 rounded-lg bg-brand px-5 py-3 font-bold text-white"><span class="material-symbols-outlined">add</span>Tambah Project</button></div><div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">${projects.length ? projects.map(p=>`<article class="card rounded-2xl border border-line bg-white p-5"><div class="flex items-start justify-between"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-3 text-primary">folder</span><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">${p.tasks.length} tasks</span></div><h3 class="mt-5 font-geist text-xl font-bold">${escape(p.name)}</h3><p class="mt-2 min-h-12 text-sm text-slate-600">${escape(p.description || 'Belum ada deskripsi project.')}</p><p class="mt-4 text-xs text-slate-500">Dibuat oleh ${escape(p.created_by)} · ${new Date(p.created_at).toLocaleDateString('id-ID')}</p><div class="mt-5 flex gap-2 border-t border-line pt-4"><a href="projects.html?project=${p.id}" class="flex-1 rounded-lg bg-brand px-3 py-2 text-center text-sm font-bold text-white">Buka Kanban</a><button onclick="editProject('${p.id}')" aria-label="Edit" class="rounded-lg border border-line px-3 text-primary"><span class="material-symbols-outlined">edit</span></button><button onclick="removeProject('${p.id}')" aria-label="Hapus" class="rounded-lg border border-line px-3 text-red-600"><span class="material-symbols-outlined">delete</span></button></div></article>`).join('') : `<div class="col-span-full rounded-2xl border border-dashed border-line bg-white p-14 text-center"><span class="material-symbols-outlined text-4xl text-primary">folder_off</span><h3 class="mt-3 font-geist text-xl font-bold">Belum ada project</h3><p class="mt-2 text-slate-600">Buat project pertama Anda untuk memulai Kanban.</p></div>`}</div>`; }
function renderBoard(){ const project = ProjectStore.get(projectId); if(!project){ location.href='projects.html'; return; } const columns=[['todo','To Do'],['progress','In Progress'],['review','Review'],['done','Done']]; const badge={Low:'bg-slate-100 text-slate-700',Medium:'bg-amber-100 text-amber-800',High:'bg-red-100 text-red-800'}; app.innerHTML=`<a href="projects.html" class="inline-flex items-center gap-1 text-sm font-semibold text-primary"><span class="material-symbols-outlined text-lg">arrow_back</span>Semua Project</a><div class="mt-4 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 class="font-geist text-3xl font-bold">${escape(project.name)}</h2><p class="mt-2 text-slate-600">${escape(project.description||'Kanban board project.')}</p></div><button onclick="newTask()" class="inline-flex items-center justify-center gap-2 rounded-lg bg-brand px-5 py-3 font-bold text-white"><span class="material-symbols-outlined">add</span>Tambah Task</button></div><div class="mt-8 grid min-w-[1000px] grid-cols-4 gap-4 overflow-x-auto pb-4">${columns.map(([status,label])=>{const tasks=project.tasks.filter(t=>t.status===status);return `<section ondragover="event.preventDefault()" ondrop="dropTask(event,'${status}')" class="rounded-2xl bg-blue-50/70 p-3"><div class="mb-3 flex items-center justify-between px-2"><h3 class="font-geist font-bold">${label}</h3><span class="rounded-full bg-white px-2 py-0.5 text-xs font-bold">${tasks.length}</span></div><div class="min-h-32 space-y-3">${tasks.length?tasks.map(t=>`<article draggable="true" ondragstart="dragTask(event,'${t.id}')" onclick="showTask('${t.id}')" class="cursor-pointer rounded-xl border border-line bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-2"><h4 class="font-geist font-bold">${escape(t.title)}</h4><span class="rounded-full px-2 py-1 text-xs font-bold ${badge[t.priority]}">${t.priority}</span></div>${t.description?`<p class="mt-2 line-clamp-2 text-sm text-slate-600">${escape(t.description)}</p>`:''}<div class="mt-4 flex justify-between text-xs text-slate-500"><span>${t.assignee?escape(t.assignee):'Unassigned'}</span><span>${t.due_date?new Date(t.due_date+'T00:00').toLocaleDateString('id-ID'):'No due date'}</span></div></article>`).join(''):`<div class="rounded-xl border border-dashed border-line p-5 text-center text-sm text-slate-500">Belum ada task</div>`}</div><button onclick="newTask('${status}')" class="mt-3 w-full rounded-lg py-2 text-sm font-bold text-primary hover:bg-white">+ Tambah Task</button></section>`}).join('')}</div>`; }
function render(){ projectId?renderBoard():renderProjects(); }
function newProject(){ formModal('Tambah Project',projectForm(), data=>{ProjectStore.createProject(Object.fromEntries(data));closeModal();render();notify('Project berhasil dibuat.');}); }
function editProject(id){const project=ProjectStore.get(id);formModal('Edit Project',projectForm(project),data=>{ProjectStore.updateProject(id,Object.fromEntries(data));closeModal();render();notify('Project diperbarui.');});}
function removeProject(id){if(confirm('Hapus project ini? Semua task di dalamnya juga akan terhapus.')){ProjectStore.deleteProject(id);render();notify('Project dihapus.');}}
function newTask(status='todo'){formModal('Tambah Task',taskForm({status,priority:'Medium'}),data=>{const v=Object.fromEntries(data);ProjectStore.createTask(projectId,v);closeModal();render();notify('Task berhasil dibuat.');});}
function showTask(taskId){const task=ProjectStore.get(projectId).tasks.find(t=>t.id===taskId);formModal('Detail Task',taskForm(task),data=>{ProjectStore.updateTask(projectId,taskId,Object.fromEntries(data));closeModal();render();notify('Task diperbarui.');}); modal.querySelector('#editor').insertAdjacentHTML('beforeend',`<button type="button" onclick="removeTask('${taskId}')" class="mt-3 text-sm font-semibold text-red-600">Hapus task</button>`);}
function removeTask(id){if(confirm('Hapus task ini?')){ProjectStore.deleteTask(projectId,id);closeModal();render();notify('Task dihapus.');}}
function dragTask(event,id){event.dataTransfer.setData('task',id);} function dropTask(event,status){ProjectStore.moveTask(projectId,event.dataTransfer.getData('task'),status);render();notify('Status task diperbarui.');}
render();
